- app/javascript/packs/application.js
- app/javascript/stylesheets/application.scss
- app/views/layouts/application.html.erb
- config/webpack/environment.js
- package.json
- yarn.lock
> Add Bootstrap

- app/assets/stylesheets/homes.scss
- app/controllers/homes_controller.rb
- app/helpers/homes_helper.rb
- app/views/homes/about.html.erb
- app/views/homes/top.html.erb
- config/environments/development.rb
- config/routes.rb
- config/webpack/environment.js
- test/controllers/homes_controller_test.rb
> Add homes_controller

- app/controllers/application_controller.rb
- app/views/devise/confirmations/new.html.erb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/email_changed.html.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_error_messages.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
- app/views/layouts/application.html.erb
- config/environments/development.rb
- db/migrate/20220517042631_devise_create_customers.rb
- db/schema.rb
> 簡単なログイン機能等実装

- .bash_profile
- config/environments/development.rb
> Admin items

- app/assets/stylesheets/admin/genres.scss
- app/controllers/admin/genres_controller.rb
- app/helpers/admin/genres_helper.rb
- app/javascript/packs/application.js
- app/models/genre.rb
- app/views/admin/genres/edit.html.erb
- app/views/admin/genres/index.html.erb
- app/views/homes/about.html.erb
- config/environments/development.rb
- config/routes.rb
- db/migrate/20220518080250_create_genres.rb
- db/schema.rb
- test/controllers/admin/genres_controller_test.rb
- test/fixtures/genres.yml
- test/models/genre_test.rb
◎ジャンル機能を追加しました！
◎Aboutページの文章追記しました！
> Admin genre

- app/assets/stylesheets/customer/items.scss
- app/controllers/customer/items_controller.rb
- app/helpers/customer/items_helper.rb
- app/models/item.rb
- app/views/customer/items/index.html.erb
- app/views/customer/items/show.html.erb
- config/routes.rb
- db/schema.rb
- test/controllers/customer/items_controller_test.rb
> [Add]customer_items

- app/assets/stylesheets/customer/carts.scss
- app/controllers/customer/carts_controller.rb
- app/controllers/customer/items_controller.rb
- app/helpers/customer/carts_helper.rb
- app/models/cart.rb
- app/models/customer.rb
- app/models/item.rb
- app/views/customer/addresses/index.html.erb
- app/views/customer/carts/all_destroy.html.erb
- app/views/customer/carts/create.html.erb
- app/views/customer/carts/destroy.html.erb
- app/views/customer/carts/index.html.erb
- app/views/customer/carts/update.html.erb
- app/views/customer/items/show.html.erb
- config/routes.rb
- db/migrate/20220520045012_create_carts.rb
- db/schema.rb
- test/controllers/customer/carts_controller_test.rb
- test/fixtures/carts.yml
- test/models/cart_test.rb
> Carts controller

- Gemfile
- Gemfile.lock
- app/controllers/customer/items_controller.rb
- app/views/admin/items/show.html.erb
- app/views/customer/items/index.html.erb
- app/views/customer/items/show.html.erb
> Customers items

- app/controllers/customer/orders_controller.rb
- app/models/order.rb
- app/views/customer/orders/index.html.erb
- app/views/customer/orders/new.html.erb
- app/views/customer/orders/show.html.erb
> Customers orders

- app/assets/stylesheets/admin/orders.scss
- app/controllers/admin/orders_controller.rb
- app/helpers/admin/orders_helper.rb
- app/models/order.rb
- app/models/order_detail.rb
- app/views/admin/orders/index.html.erb
- app/views/admin/orders/show.html.erb
- config/routes.rb
- test/controllers/admin/orders_controller_test.rb
> Admin orders

- app/views/customer/customers/show.html.erb
- app/views/customer/orders/index.html.erb
- app/views/customer/orders/show.html.erb
> [Update]修正

- app/views/customer/carts/index.html.erb
- app/views/layouts/application.html.erb
> マイページのリンク先修正、カートID修正

- app/views/customer/items/index.html.erb
> [update]customers_item

- app/controllers/admin/items_controller.rb
- app/views/admin/items/edit.html.erb
> 商品削除ボタンの実装

- config/application.rb
- config/locales/ja.yml
- config/locales/models/ja.yml
> validation

- app/controllers/customer/addresses_controller.rb
> comp_validation

- app/controllers/customer/carts_controller.rb
- app/views/customer/items/show.html.erb
> [Add]error message

- app/views/layouts/application.html.erb
> admin_header

- app/models/item.rb
- app/views/admin/items/new.html.erb
- config/locales/models/ja.yml
> [update]エラーメッセージ

- app/views/layouts/application.html.erb
> fix_admin_header

- app/controllers/admin/items_controller.rb
> [update]商品新規登録の遷移先変更

- app/controllers/admin/orders_controller.rb
- app/controllers/customer/orders_controller.rb
- app/views/admin/orders/show.html.erb
- app/views/customer/orders/index.html.erb
> [update]注文履歴一覧最新の投稿からに変更

- app/controllers/admin/orders_controller.rb
> [update]orders_controller

- app/views/admin/customers/show.html.erb
- app/views/admin/genres/index.html.erb
- app/views/admin/items/edit.html.erb
- app/views/admin/items/new.html.erb
- app/views/admin/orders/show.html.erb
- app/views/customer/addresses/index.html.erb
- app/views/customer/carts/index.html.erb
- app/views/customer/customers/edit.html.erb
- app/views/customer/customers/show.html.erb
- app/views/customer/items/index.html.erb
- app/views/customer/items/show.html.erb
- app/views/customer/orders/confirm.html.erb
- app/views/customer/orders/index.html.erb
- app/views/customer/orders/new.html.erb
- app/views/customer/orders/show.html.erb
- app/views/homes/top.html.erb
- app/views/layouts/application.html.erb
- config/locales/models/ja.yml
- config/routes.rb
> [update]インデント修正

- app/views/layouts/application.html.erb
- config/locales/models/ja.yml
- config/routes.rb
> [update]ja.yml

- app/views/admin/sessions/new.html.erb
- app/views/admin/shared/_links.html.erb
- app/views/customer/orders/show.html.erb
- app/views/customer/registrations/new.html.erb
- app/views/customer/shared/_links.html.erb
- config/application.rb
> [update]Eメール修正、数字表記

- app/views/customer/registrations/new.html.erb
> [Add]プレースホルダ―

- app/views/admin/orders/show.html.erb
- app/views/admin/sessions/new.html.erb
- app/views/customer/orders/confirm.html.erb
- app/views/customer/orders/show.html.erb
- app/views/customer/registrations/new.html.erb
> [update]confirmの数値修正、管理者ログインの日本語訳、配送先の宛名記述変更
